-- CREATE DATABASE IF NOT EXISTS mi_empresa;

-- USE mi_empresa;

CREATE TABLE employee (
  id INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) DEFAULT NULL,
  last_name VARCHAR(45) DEFAULT NULL,
  dni VARCHAR(8) DEFAULT NULL,
  phone VARCHAR(9) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  position VARCHAR(45) DEFAULT NULL,
  salary INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
);

DESCRIBE employee;

CREATE TABLE clients (
  id INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) DEFAULT NULL,
  last_name VARCHAR(45) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(9) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

DESCRIBE clients;


